### PR TITLE
Fixed @@change-password to accept current password containing non-ascii ...

### PR DESCRIPTION
**Pull request by sgeulette**
...chars, also new password in the same case.
Fix issue #35

### CODE REVIEW

**Comment by sgeulette** [comment]
Hello @tomgross @tisto @cewing , someone to merge ?

**Comment by gforcada** [comment]
@sgeulette let's see if jenkins likes it or not: http://jenkins.plone.org/job/pull-request/126/

And :+1: for adding tests and :+1: for the change log entries!

**Comment by sgeulette** [comment]
The plone.app.users tests on master all pass :ok_hand:

**Comment by gforcada** [comment]
@sgeulette I don't see the same: http://jenkins.plone.org/job/pull-request/126/testReport/ Let's give it another try: http://jenkins.plone.org/job/pull-request/132/

**Comment by gforcada** [comment]
Finally it got green, merging!

**Pull request merged**
