### PR TITLE
Fixed @@change-password to accept current password containing non-ascii ...

### PR DESCRIPTION
**Pull request by sgeulette**
...chars, also new password. Resolve issue #35 
Same behaviour than when registering

### CODE REVIEW

**Comment by sgeulette** [comment]
Hello @tomgross @tisto @cewing , someone to merge ?

**Comment by gforcada** [comment]
@sgeulette same as like the other pull request, let's check jenkins: http://jenkins.plone.org/job/pull-request/127

And again :+1: for changelog and :+1: for tests! ;)

**Comment by sgeulette** [comment]
The plone.app.users tests for 1.2.x branch all pass :ok_hand:

**Comment by gforcada** [comment]
Let's give it another try: http://jenkins.plone.org/job/pull-request/133/

**Comment by gforcada** [comment]
Sorry! I was testing this pull request against Plone 5 not Plone 4... now that should work: http://jenkins.plone.org/view/All/job/pull-request-4.3/9

**Comment by sgeulette** [comment]
Hi gforcada, one error too but not related to plone.app.users...

**Comment by jensens** [comment]
http://jenkins.plone.org/view/All/job/pull-request/155/

**Comment by sgeulette** [comment]
Hi @jensens @gforcada , the 1.2.x branch runs on plone 4.3.x. I run again yesterday the tests (http://jenkins.plone.org/view/All/job/pull-request-4.3/16), that give 2 errors not related to my changes I think. 
http://jenkins.plone.org/view/All/job/pull-request-4.3/18 about other changes gives same robot errors, mayby due to a robot test made to quickly.

**Comment by jensens** [comment]
see plone/plone.app.dexterity#163

**Comment by jensens** [comment]
so let it run again, now Plone 4.3 http://jenkins.plone.org/view/All/job/pull-request-4.3/20/

**Comment by sgeulette** [comment]
I have run robot tests locally with buildout.coredev and my plone.app.users fork.
Running "env ROBOT_BROWSER=GoogleChrome bin/test --all -s plone.app.dexterity" gives me no error. 
Running "env ROBOT_BROWSER=GoogleChrome bin/test --all -s plone.schemaeditor" gives me 1 error but on another test and without my fork too !

**Comment by jensens** [comment]
@gforcada @tisto - i dont understand whats going on here, can one of you take over please?

**Comment by gforcada** [comment]
@jensens let me try something...

**Comment by gforcada** [comment]
sorry it didn't work, no idea what's going on there :S

**Comment by gotcha** [comment]
All tests pass in http://jenkins.plone.org/view/All/job/pull-request-4.3/36/.

(The job is still red because it fails running alltests-at which is 5.0 only.)

**Pull request merged**
