### PR TITLE
Consider group.id as untrusted source (e.g. ldap) and encode it accordingly

### PR DESCRIPTION
**Pull request by pbauer**

### CODE REVIEW

**Comment by jensens** [comment]
is this something important or can we close this as stalled?

**Comment by mauritsvanrees** [comment]
@pbauer Do you remember what problems you were getting? Did LDAP return titles with line endings maybe?

**Comment by ale-rt** [comment]
Reading the patch it seems to me that this is some protection against unicode/str issues on Python 2.
The patch looks good to me but it is probably not needed anymore on Python 3.

**Comment by jensens** [comment]
I close this request for now. If you think this is wrong speak up and reopen. If you plan to work further on this, reopen and go on.

**Pull request closed without merging**
