### PR TITLE
remove CMFDefault dependency

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by gforcada** [comment]
Running test on http://jenkins.plone.org/job/pull-request/85/console

**Comment by gforcada** [comment]
Would it make sense to create a cfg file on buildout.coredev to keep all these branches together and not loose them? In the same way you did with PloneTestCase?

**Comment by gforcada** [comment]
Tests did pass, so merged! Great work, as usual!

**Comment by tomgross** [comment]
There is a config in coredev:
https://github.com/plone/buildout.coredev/blob/5.0/plips/plip-nocmfdefault.cfg

**Pull request merged**
