### PR TITLE
Plip13350 edit member schema ttw post z3cform merge

### PR DESCRIPTION
**Pull request by ebrehault**
Hi @frapell, I think it is quite ok now, could you have a look ?

### CODE REVIEW

**Comment by ebrehault** [comment]
By the way, tests are all passing but one: when editing an existing field with the schema editor, its label is not translated.

**Comment by tisto** [comment]
@ebrehault It would be awesome if we could add some robot framework tests for this functionality. Also to document how this is supposed to work. I'd be happy to help with the setup if necessary.

**Comment by tisto** [comment]
@ebrehault As discussed during the FWT meeting yesterday, I started to create the Jenkins pull request job and tested it with your pull request:

http://jenkins.plone.org/job/plone-5.0-python-2.7-test-pull-request/2/testReport/
http://jenkins.plone.org/job/plone-5.0-python-2.7-test-pull-request/2/console

It seems there are two test failures:

/home/jenkins/workspace/plone-5.0-python-2.7-test-pull-request/src/Products.CMFPlone/Products/CMFPlone/tests/csrf.txt", line 169

src/plone.app.users/plone/app/users/tests/flexible_user_registration.rst", line 42, in flexible_user_registration.rst

Just let me know when you fixed those failing tests. I will run the job again then.

**Comment by ebrehault** [comment]
Oh right, we miss a menu which was provided by plone.app.controlpanel in this branch https://github.com/plone/plone.app.controlpanel/tree/plip13350-edit-member-schema-ttw but it is now totally obselete (due to z3Cform changes). I will push the needed changes on plone.app.controlpanel ASAP.

**Comment by gforcada** [comment]
Would it be possible to tidy up the commits? 67 commits is way too much to really be able to review things, specially if there are "typo" kind of commits :)

**Comment by ebrehault** [comment]
@tisto I have updated the impacted controlpanel templates (that's not in p.a.controlpanel anymore but in Products.CMFPlone), here is the branch: https://github.com/plone/Products.CMFPlone/tree/plip13350-edit-member-schema-ttw
Note: I am not sure what is the good practice here, shall I mention this branch in the buildout.cfg, and then we remove it once merged?

**Comment by tisto** [comment]
@ebrehault I don't fully understand. Do your changes depend on another package branch? If not we can just test the branch and merge it when Jenkins is green.

**Comment by tisto** [comment]
Let's see if the build is green now: http://jenkins.plone.org/job/plone-5.0-python-2.7-test-pull-request/3/console

**Comment by ebrehault** [comment]
@tisto I have just added a Robot test

**Comment by ebrehault** [comment]
@tisto yes it depends on another package branch (some of the control panels templates displaying the link to the "Member fields" page are not part of p.a.users, they are in Products.CMFPlone)

**Comment by frapell** [comment]
@ebrehault sorry, I was on vacation and *just* got back, I will be helping review this over the weekend.

As per your question, we used to create a .cfg file for buildout.coredev which pulled all the needed branches for testing the PLIP. That way is easy to know which packages need to be merged from their respective branches.

Look at https://github.com/plone/buildout.coredev/blob/5.0/plips/plip13350-edit-member-schema-ttw.cfg

**Comment by ebrehault** [comment]
@frapell ok thank you, that's what I was looking for.
@tisto here is the updated buildout: https://github.com/plone/buildout.coredev/blob/5.0/plips/plip13350-edit-member-schema-ttw.cfg , (will it be automatically used by Jenkins?)

**Comment by tisto** [comment]
@ebrehault No, Jenkins will not automatically pick up that PLIP job. I will look into it.

**Comment by tisto** [comment]
I created a PLIP job: http://jenkins.plone.org/job/plip-13350-edit-member-schema-ttw.cfg

**Comment by frapell** [comment]
@ebrehault I have added my review on this PLIP here https://github.com/plone/buildout.coredev/blob/5.0/plips/reviews/plip13350-review-frapell.rst

**Comment by ebrehault** [comment]
Thank you very much @frapell for this review, I am on it.
@gforcada : about tidying the commits, I agree it would be better, I will try to do that (by starting from scratch in a new branch).

**Comment by ebrehault** [comment]
Hi @frapell , please have a look to the changes I made after your review when you have a moment.

**Comment by frapell** [comment]
@ebrehault Will do so this weekend! sorry the delay :(

**Comment by frapell** [comment]
@ebrehault I have updated my review, it can be seen in https://github.com/plone/buildout.coredev/blob/b0f0d74bb6b96b0293883bf9aff95805f19c8533/plips/reviews/plip13350-review-frapell.rst

**Comment by gforcada** [comment]
@ebrehault the branch needs a rebase and most probably some git history cleanup?

**Comment by ebrehault** [comment]
@gforcada definitely :)

**Comment by ebrehault** [comment]
Hi Franco,

Thank you for the review.
As discussed with Ramon, I have put your remarks into issues in Products.CMFPlone, so we can track them with all the Plone 5 milestones issues: https://github.com/plone/Products.CMFPlone/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Plone+5%22

Some of your points where questions, here are my answers:

- *The import step is not ran automatically when creating a site from scratch, so by default, the member schema will only have "fullname" and "email".* Yes true, and to me, that's fine.

- *I see a "Date" field type, which allows you to add a field for just date. There is no way to make that a "Datetime". Is there a reason for this?* I though date was enough (and I do not to provide a too long list of field types, for simplicity sake)

- *When adding a "Rich Text" field, the TinyMCE editor is not visible for anonymous when registering* I do not know what to do about that, I guess the easiest short-term solution is to remove Rich text field.

- *Do we have a limitation of just 1 Image field?* yes indeed, Plone member data can just store 1 file (the portrait), so we need to block extra image addition in the editor.

- *Would it make sense to have the ALLOWED_FIELDS coming from the registry or somewhere easy to change without the need to monkey patch?* I am afraid that some field types could easily cause big problems, so I prefer to let this list hard-coded here.

- *Why do we need ProtectedTextLine and ProtectedEmail? Can't the "protection" come from an attribute in the schema definition? this way we can also make it possible define additional fields that cannot be edited or removed (Avoid users accidentally removing sensitive fields)* I spend a lot of time on that point actually. And my current understanding is that is the only way to achieve that with `plone.schemaeditor`, but maybe I am missing something.

**Comment by frapell** [comment]
Hey Erik, here are my thoughts

  * The import step is not ran automatically when creating a site from scratch, so by default, the member schema will only have "fullname" and "email". 

    EB: Yes true, and to me, that's fine.

    FP:  Well, maybe we should ask opinions here... I would say to run the profile on install time... that way a new site from scratch will have the same fields a 4.3 instance has... but that's my opinion...

  * I see a "Date" field type, which allows you to add a field for just date. There is no way to make that a "Datetime". Is there a reason for this?

    EB: I though date was enough (and I do not to provide a too long list of field types, for simplicity sake)
    FP: I think it was possible to provide Datetime as field type, but control from the widget if the "time" part would show up or not, maybe we should try that? I don't know the need of any of the fields are, I try to think of happier developers when have to comply with client requests 

  * When adding a "Rich Text" field, the TinyMCE editor is not visible for anonymous when registering 

    EB: I do not know what to do about that, I guess the easiest short-term solution is to remove Rich text field.

    FP: I'm pretty sure this is because the Javascript that holds TinyMCE, is only available for authenticated. Maybe @bloodbare can provide his thoughts here? would it be possible to show the TinyMCE for not authenticated visitors in the @@register form? I do like having the RichText field as possible field for the member profile (for bio input for instance). If there is no way we can make it work, maybe we can limit the visibility of RichText fields for just the profile form? (it works fine in there)

  * Do we have a limitation of just 1 Image field? 

    EB: yes indeed, Plone member data can just store 1 file (the portrait), so we need to block extra image addition in the editor.

    FP: Sounds good to me

  * Would it make sense to have the ALLOWED_FIELDS coming from the registry or somewhere easy to change without the need to monkey patch? 

    EB: I am afraid that some field types could easily cause big problems, so I prefer to let this list hard-coded here.

    FP: Well... the whole point of all this work is because it is a fairly common thing for us to customize this for different projects... If we can have this list coming from a registry key, it would be so much easier to manage it (say, in case you don't want to allow RichText as field, or include Datetime, etc) than having to monkey patch...

  * Why do we need ProtectedTextLine and ProtectedEmail? Can't the "protection" come from an attribute in the schema definition? this way we can also make it possible define additional fields that cannot be edited or removed (Avoid users accidentally removing sensitive fields)

    EB: I spent a lot of time on that point actually. And my current understanding is that is the only way to achieve that with plone.schemaeditor, but maybe I am missing something.

    FP: Right... well, too bad, this will have to do

**Comment by ebrehault** [comment]
Ok thanks.
For your information, @bloodbare would like to have this PLIP merged into 5.0, so my objective is to clean up all the blocking issues (tests, documentation, bugs with the editor, bugs with the various field types) so we get something stable soon, and we will address the other points later.

**Comment by ebrehault** [comment]
@frapell About importing profile on install time so we get the 4.3 usual field at start, I think you are right.
But I am wondering where I could do that. I guess the right way is to put the userchema.xml file into the Products.CMFPlone profile, what do you think?

**Comment by frapell** [comment]
@ebrehault I would list the profile in some metadata.xml... I would do it in https://github.com/plone/Products.CMFPlone/blob/plip13350-edit-member-schema-ttw-post-z3cform-merge/Products/CMFPlone/profiles/dependencies/metadata.xml

**Comment by ebrehault** [comment]
Right.
Done

**Comment by ebrehault** [comment]
@frapell I have fixed all the bugs + add missing tests + document import/export (in the README).
If you think the PR is OK now, do not merge it, I would prefer to create a new branch to rebase all the changes on a cleaner way.

**Comment by ebrehault** [comment]
@frapell here is the rebased branch: https://github.com/plone/plone.app.users/tree/plip13350-edit-member-schema-ttw-rebase

**Pull request closed without merging**
